---
title: "Practical Machine Learning - Course Project"
author: "Anastassiya Zidkova"
date: "23.5.2015"
output: html_document
---

##Abstract

##Introduction

##Enabling parallelization
Before performing any analysis we 
https://anastazie.github.io/anastazie/PracticalMachineLearning/CourseProject.html

```{r}
library(doParallel);
rCluster <- makePSOCKcluster(4);
registerDoParallel(rCluster);
```


##Cleaning data
Before performing any analysis we 
https://anastazie.github.io/anastazie/PracticalMachineLearning/CourseProject.html

```{r}
setwd("~/Documents/Coursera/PracticalMachineLearning/CourseProject")
train <- read.csv("pml-training.csv", head=T, na.strings=c("NA",""))
valid <- read.csv("pml-testing.csv", head=T, na.strings=c("NA",""))
train2 <- train[,colSums(is.na(train)) == 0] 
```

##Creating training and testing datasets

```{r}
library(caret)
set.seed(17)
trainL <- createDataPartition(y=train2$classe, p=0.7, list=FALSE)
train3 <- train2[trainL,]
test <- train2[-trainL,]
dim(train3); dim(test)
```

##Fitting linear regression model

```{r}
set.seed(17)
modFitAll<- train(classe ~ .,data=train3,method="rf", trControl = trainControl(method = "cv", allowParallel =TRUE))
pred <- predict(modFitAll, test)
modFitAll
cfM <- confusionMatrix(pred, test$classe)
cfM$table
```
##Predicting values of validation set

```{r}
set.seed(17)
modFitAll<- train(classe ~ .,data=train3,method="rf",  trControl = trainControl(method = "cv", allowParallel =TRUE))
pred <- predict(modFitAll, test)
qplot(classe,pred,data=test)

```

##Conclusion

##References

